import React from 'react'

function Privacy() {
    return (
        <div class="privacy p-5 m-0 mt-5 bg-secondary text-info">
            <div class="">
                <h2 class="text-center mb-5 pb-3 mt-5 text-info">Privacy Policy</h2>
                <h5>Your Privacy Rights Are Important To Us.</h5>
                <p>We at iNovate OS know that you care about how your personal information is used and shared, and we take your privacy seriously.</p> <br />
<h6>You will learn more about our Privacy Policy in this article.</h6> <br /><br />
<p>By using or accessing the Services in any manner, you acknowledge that you accept the practices and policies outlined in this Privacy Policy, and you hereby consent that we will collect, use, and share your information in the following ways. Remember that your use of iSchoolManager’s Services is at all times subject to the Terms of Use, which incorporates this Privacy Policy. Any terms we use in this Policy without defining them have the definitions given to them in the Terms of Use. </p><br />
<h3>What does this Privacy Policy cover? </h3>
<p>This Privacy Policy covers our treatment of personally identifiable information (“Personal Information”) that we gather when you are accessing or using our Services, but not to the practices of companies we don’t own or control, or people that we don’t manage. We gather various types of Personal Information from our users, as explained in more detail below, and we use this Personal Information internally in connection with our Services, including to personalize, provide, and improve our services, to allow you to set up a user account and profile, to contact you and allow other users to contact you, to fulfill your requests for certain products and services, and to analyze how you use the Services. </p><br />
<h3>Will iSchoolManager ever change this Privacy Policy?</h3>
<p> We’re constantly trying to improve our Services, so we may need to change this Privacy Policy from time to time as well, but we will alert you to changes by placing a notice on the <code>www.iSchoolManager.com</code> website, by sending you an email, and/or by some other means. <br />Please note that if you’ve opted not to receive legal notice emails from us (or you haven’t provided us with your email address), those legal notices will still govern your use of the Services, and you are still responsible for reading and understanding them. <br />If you use the Services after any changes to the Privacy Policy have been posted, that means you agree to all of the changes. </p><br />
<h3>What Information does iSchoolManager Collect?</h3>
<p> Information You Provide to Us We receive and store any information you knowingly provide to us. For example, through the registration process and/or through your account settings, we may collect Personal Information such as your name, email address, picture, and phone number. <br />Certain information may be required to register with us or to take advantage of some of our features. We may receive Personal Information about you from the school you are associated with (or, in the case of students, from your teacher or parent). This privacy policy applies to our use of such Personal Information as well. We may communicate with you if you have (or another user has) provided us the means to do so. For example, if you’ve given us your email address, we may email you about your use of the Services. <br />Also, we may receive a confirmation when you open an email from us. This confirmation helps us make our communications with you more interesting and improve our services. If you do not wish to receive communications from us, please indicate by emailing <code>support@inovateos.com</code>.<br />
 Information Collected Automatically Whenever you interact with our Services, we automatically receive and record information on our server logs from your browser or device, which may include your IP address, device identification, “cookie” information, the type of browser and/or device you’re using to access our Services, and the page or feature you requested. “Cookies” are identifiers we transfer to your browser or device that allow us to recognize your browser or device and tell us how and when pages and features in our Services are visited and by how many people. You may be able to change the preferences on your browser or device to prevent or limit your device’s acceptance of cookies, but this may prevent you from taking advantage of some of our features. We may use this data to customize content for you that we think you might like, based on your usage patterns. <br />We may also use it to improve the Services – for example, this data can tell us how often users use a particular feature of the Services, and we can use that knowledge to make the Services interesting to as many users as possible. </p><br />
<h3>Will iSchoolManager Share Any of the Personal Information it Receives?</h3>
<p> We do not rent or sell your Personal Information in personally identifiable form to anyone. We may share your Personal Information as described in this section: <br />
Schools As described above, Personal Information may be disclosed about individuals (including student, parent, and teacher users of the Services) from the school such person is or has been associated with. We do not control how schools use or disclose such information. For example, if you have a student account, the Services may permit the school, teacher, or parent account(s) associated with your account to view all activity and information associated with your account. iSchoolManager itself will not disclose such Personal Information to third parties except as otherwise described in this Privacy Policy. <br />
Information that’s no longer personally identifiable. We may provide aggregate usage information to our partners, who may use such information to understand how often and in what ways people use our Services, so that they, too, can provide you with an optimal online experience. However, we never disclose aggregate usage information to a partner in a manner that would identify you personally, as an individual person. Agents We employ other companies and people to perform tasks on our behalf and need to share your information with them to provide products or services to you; for example, we may use a payment processing company to receive and process payments we receive from schools, or we may use an analytics or customer service company that helps us improve how the Services function. <br />Unless we tell you differently, our agents do not have any right to use the Personal Information we share with them beyond what is necessary to assist us. <br />
Protection of iSchoolManager and Others We reserve the right to access, read, preserve, and disclose any information that we believe is necessary to comply with law or court order; enforce or apply our Terms of Use and other agreements; or protect the rights, property, or safety of iSchoolManager, our employees, our users, or others.</p><br />
<h3> Is Personal Information about me secure? </h3>
<p>Your account is protected by a password for your privacy and security. You must prevent unauthorized access to your account and Personal Information by selecting and protecting your password appropriately and limiting access to your computer or device and browser by signing off after you have finished accessing your account. <br />We endeavor to protect the privacy of your account and other Personal Information we hold in our records, but unfortunately, we cannot guarantee complete security. Unauthorized entry or use, hardware or software failure, and other factors, may compromise the security of user information at any time. </p><br />
<h3>What Personal Information can I access?</h3>
<p> If you have a school account, you may access, and, in some cases, edit or delete information you’ve provided to us about your school or any School-Provided Information. If you have a student, teacher, or parent account, you may have the ability to suggest edits to School-Provided Information we have on file about you, but again, iSchoolManager is not required to delete or correct School-Provided Student Information at the request of anyone except the school that originally provided such information. <br />You may, however, be able to access, edit, and delete certain information you’ve provided to us about yourself, using the functionality of the Services. The information you can view, update, and delete about you may change as the Services change. If you have any questions about viewing or updating information we have on file about you, please contact your school account administrator if it concerns School-Provided Information; otherwise, you may contact iSchoolManager at <code>support@inovateos.com</code>.</p><br />
 <h3>What choices do I have?</h3>
<p> You can always opt not to disclose information to us, but keep in mind some information may be needed to register with us or to take advantage of some of our features. You may be able to add, update, or delete information as explained above. When you update information, however, we may maintain a copy of the unrevised information in our records.<br /> You may request deletion of your account by contacting the applicable school that originally created the account. Some information may remain in our records after your deletion of such information from your account. We may use any aggregated data derived from or incorporating your Personal Information after you update or delete it, but not in a manner that would identify you personally, and only in accordance with the Terms.</p><br />
<h3> What if I have questions about this policy?</h3>
<p> If you have any questions or concerns regarding our privacy policies, please send us a detailed message to <code>support@inovateos.com</code>, and we will try to resolve your concerns.</p>
            </div>
            
        </div>
    )
}

export default Privacy
