import React from 'react'

function Terms() {
    return (
        <div class="bg-grey p-3 pt-5 mt-5 m-auto m-lg-5 p-lg-5 text-center position-relative">
                <h2 class="pb-4 pt-5">Terms of Use</h2>
                <div class="accordion d-inline" id="accordionFlushExample1">

          <div class="accordion-item">
            <h2 class="accordion-header" id="flush-heading1">
              <button class="accordion-button p-lg-4 collapsed text-dark bg-info" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse1" aria-expanded="false" aria-controls="flush-collapse1">
                Open to read the terms.
              </button>
            </h2>
            
          <div id="flush-collapse1" class="accordion-collapse collapse" aria-labelledby="flush-heading1" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body text-left">
                            <p class="text-center">IMPORTANT!</p>
                            <p>For students, please review this terms of agreement with a parent or guardian so that you both understand how iSchoolManager works and what restrictions apply to your use of our services. It is advisable to always get a guardian’s permission before going online. </p>
 <br /> <h3>Terms of Use</h3>

<p>Welcome to the iSchoolManager website! Kindly read the rules and restrictions that govern your use of our website(s), products, services and applications (“the Services”). If you have any questions, comments, or concerns regarding these terms or any of our Services, kindly contact us at <code>info@inovateos.com</code></p> 
                            <p>These Terms of Use (the “Terms”) are a binding contract between you and iNovate Operating System Limited (“iSchoolManager,” “we” and “us”). You must agree to and accept all of the Terms, or you don’t have the right to use the Services. Your using the Services in any way means that you have agreed to all of the Terms,
                            and these Terms will remain in effect while you use the Services. These Terms include the provisions in this document, as well as those in the <a href="Privacy">Privacy policy</a>.</p> <br />
                            <h3>What are the basics of using iSchoolManager? </h3>
<p>You may be required to sign up for an account, and select a password and user name. You promise to provide us with accurate, complete, and updated registration information about yourself. You may not select as your iSchoolManager User ID a name that you don’t have the right to use, or another person’s name with the intent to impersonate that person. You may not transfer your account to anyone else without our prior written permission. You represent and warrant that you are of legal age to form a binding contract (or if not, you have received your parent’s or guardian’s permission to use the Services and gotten your parent or guardian to agree to these Terms on your behalf). If you’re agreeing to these Terms on behalf of an organization (for example, if you’re a school administrator agreeing to these Terms on behalf of your school, you represent and warrant that you are authorized to agree to these Terms on that organization or entity’s behalf and bind them to these Terms (in which case, the references to “you” and “your” in these Terms, except for in this sentence, refer to that organization or entity). You will only use the Services for your own internal, personal, non-commercial, educational use, and only in a manner that complies with all laws that apply to you. If your use of the Services is prohibited by applicable laws, then you aren’t authorized to use the Services. We can’t and won’t be responsible for your using the Services in a way that breaks the law. <br /> <br />
You will not share your account or password with anyone, and you must protect the security of your account and your password. You are responsible for any activity associated with your account, and, if you have a school account, you are responsible for ensuring that each student, teacher, and parent account associated with your account complies with all of the restrictions set forth in these Terms. <br /><br />
Your use of the Services is subject to the following additional restrictions: <br />
You represent, warrant, and agree that you will not contribute any Content or User Submission (each of those terms is defined below) or otherwise use the Services or interact with the Services in a manner that: Infringes or violates the intellectual property rights or any other rights of anyone else (including iSchoolManager); <br />
Violates any law or regulation, including any applicable export control laws; <br />
Is harmful, fraudulent, deceptive, threatening, harassing, defamatory, obscene, or otherwise objectionable; <br />
Jeopardizes the security of your iSchoolManager account or anyone else’s (such as allowing someone else to log in to the Services as you); <br />
Attempts, in any manner, to obtain the password, account, or other security information from any other user; <br />
Violates the security of any computer network, or cracks any passwords or security encryption codes; <br />
Runs Maillist, Listserv, any form of auto-responder or “spam” on the Services, or any processes that run or are activated while you are not logged into the Services, or that otherwise interfere with the proper working of the Services (including by placing an unreasonable load on the Services’ infrastructure); <br />
“Crawls,” “scrapes,” or “spiders” any page, data, or portion of or relating to the Services or Content (through use of manual or automated means); <br />
Copy or store any significant portion of the Content; <br />
Decompiles, reverse engineers, or otherwise attempts to obtain the source code or underlying ideas or information of or relating to the Services. A violation of any of the foregoing is grounds for termination of your right to use or access the Services. What are my rights in the Services? The materials displayed or performed or available on or through the Services, including, but not limited to, text, graphics, data, articles, photos, images, illustrations, User Submissions, and so forth (all of the foregoing, the “Content”) are protected by copyright and/or other intellectual property laws. You promise to abide by all copyright notices, trademark rules, information, and restrictions contained in any Content you access through the Services, and you won’t use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell or otherwise exploit for any purpose any Content not owned by you,<br />
 (i) without the prior consent of the owner of that Content or <br />
(ii) in a way that violates someone else’s (including iSchoolManager’s) rights.<br /> <br />

 You understand that iSchoolManager owns the Services. You won’t modify, publish, transmit, participate in the transfer or sale of, reproduce, create derivative works based on, or otherwise exploit any of the Services, except as expressly set forth herein. The Services may allow you to copy or download certain Content; please remember that just because this functionality exists, doesn’t mean that all the restrictions above don’t apply – they do!</p> <br />

<h3>Do I have to grant any licenses to iSchoolManager or to other users?</h3> 
<p> Anything you post, upload, share, store, or otherwise provide through the Services is your “User Submission.” Some User Submissions are viewable by other users. In order to display your User Submissions on the Services, and to allow other users to enjoy them (where applicable), you grant us certain rights in those User Submissions.<br /> Please note that all of the following licenses are subject to our Privacy Policy to the extent they relate to User Submissions that are also your personally-identifiable information. For all User Submissions, you hereby grant iSchoolManager a license to translate, modify (for technical purposes, for example making sure your content is viewable on an iPhone as well as a computer) and reproduce and otherwise act with respect to such User Submissions, in each case to enable us to operate the Services, as described in more detail below. <br />
This is a license only – your ownership in User Submissions is not affected. If you store a User Submission in your own personal iSchoolManager account, in a manner that is not viewable by any other user except you (a “Personal User Submission”), you grant iSchoolManager the license above, as well as a license to display, perform, and distribute your Personal User Submission for the sole purpose of making that Personal User Submission accessible to you and providing the Services necessary to do so. <br />
If you share a User Submission only in a manner that only certain specified users can view (for example, inputting Educational Records that can be viewed by teachers associated with your school)(a “Limited Audience User Submission”), then you grant iSchoolManager the licenses above, as well as a license to display, perform, and distribute your Limited Audience User Submission for the sole purpose of making that Limited Audience User Submission accessible to such other specified users, and providing the Services necessary to do so. <br />
Also, you grant such other specified users a license to access that Limited Audience User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services. If you share a User Submission publicly on the Services and/or in a manner that more than just you or certain specified users can view (for example, on a public message board), or if you provide us (in a direct email or otherwise) with any feedback, suggestions, improvements, enhancements, and/or feature requests relating to the Services (each of the foregoing, a “Public User Submission”), then you grant iSchoolManager the licenses above, as well as a license to display, perform, and distribute your Public User Submission for the purpose of making that Public User Submission accessible to all iSchoolManager users and providing the Services necessary to do so, as well as all other rights necessary to use and exercise all rights in that Public User Submission in connection with the Services and/or otherwise in connection with iSchoolManager’s business. <br />
Also, you grant all other users of the Services a license to access that Public User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services. You agree that the licenses you grant are royalty-free, perpetual, sublicense-able, irrevocable, and worldwide, provided that when you delete your iSchoolManager account, we will stop displaying your User Submissions (other than Public User Submissions, which may remain fully available) to other users (if applicable), but you understand and agree that it may not be possible to completely delete that content from iSchoolManager’s records, and that your User Submissions may remain viewable elsewhere to the extent that they were copied or stored by other users. <br />
Notwithstanding the foregoing, please be aware that information about a student (including Educational Records) that is provided by the school, or teacher (“School-Provided Student Information”) cannot be deleted by the student or parent. If you are a student or parent and would like to have School-Provided Student Information corrected or deleted, please direct your request to the applicable school, or teacher; iSchoolManager will not delete or correct that information on your behalf. <br /> 

Finally, you understand and agree that iSchoolManager, in performing the required technical steps to provide the Services to our users (including you), may need to make changes to your User Submissions to conform and adapt those User Submissions to the technical requirements of connection networks, devices, services, or media, and the foregoing licenses include the rights to do so. </p><br /> <br />


<h3>Who is responsible for what I see and do on the Services?</h3>
<p> Any information or content publicly posted or privately transmitted through the Services is the sole responsibility of the person from whom such content originated, and you access all such information and content at your own risk, and we aren’t liable for any errors or omissions in that information or content or for any damages or loss you might suffer in connection with it. We cannot control and have no duty to take any action regarding how you may interpret and use the Content or what actions you may take as a result of having been exposed to the Content, and you hereby release us from all liability for you having acquired or not acquired Content through the Services. We can’t guarantee the identity of any users with whom you interact with while using the Services and are not responsible for which users gain access to the Services. But that doesn’t mean we do not take security seriously: <br />
students are only permitted to access the Services in connection with a school account, and we require all users (including teachers and schools) to guard their login information with the appropriate confidentiality, as described above. <br />
You are responsible for all Content you contribute, in any manner, to the Services, and you represent and warrant you have all rights necessary to do so, in the manner in which you contribute it. You will keep all your registration information accurate and current. You are responsible for all your activity in connection with the Services. The Services may contain links or connections to third party websites or services that are not owned or controlled by iSchoolManager. <br /><br />
When you access third party websites or use third party services, you accept that there are risks in doing so, and that iSchoolManager is not responsible for such risks. <br />
We encourage you to be aware when you leave the Services and to read the terms and conditions and privacy policy of each third party website or service that you visit or use. <br />
iSchoolManager has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of or opinions expressed in any third party websites or by any third party that you interact with through the Services. In addition, iSchoolManager will not and cannot monitor, verify, censor or edit the content of any third party site or service. <br />
By using the Services, you release and hold us harmless from any and all liability arising from your use of any third party website or service. Your interactions with organizations and/or individuals found on or through the Services, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals. <br /><br />
You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that iSchoolManager shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings. If there is a dispute between participants on this site, or between users and any third party, you agree that iSchoolManager is under no obligation to become involved. In the event that you have a dispute with one or more other users, you release iSchoolManager, its officers, employees, agents, and successors from claims, demands, and damages of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our Services. </p><br />

<h3>Will iSchoolManager ever change the Services?</h3>
<p> We are always trying to improve the Services, so there may be changes over time. We may suspend or discontinue any part of the Services, or we may introduce new features or impose limits on certain features or restrict access to parts or all of the Services. We’ll try to give you notice when we make a material change to the Services that would adversely affect you, but this isn’t always practical. Similarly, we reserve the right to remove any Content from the Services at any time, for any reason (including, but not limited to, if someone alleges you contributed that Content in violation of these Terms), in our sole discretion, and without notice; provided that the foregoing does not require iSchoolManager to correct or delete School-Provided Student Information, as described above. </p><br />

<h3>Does iSchoolManager cost anything?</h3>
<p> Student, parent, and teacher accounts for the Services are currently free, but are only offered in connection with your associated school paying for a subscription (as described below). We reserve the right to charge for certain or all Services in the future. We will notify you before any Services you are then using begin carrying a fee, and if you wish to continue using such Services, you must pay all applicable fees for such Services. <br />
School accounts are offered on a subscription basis (the “Subscription”); the length of the agreement (the “Subscription Term”), the estimated student enrollment (the “Estimated Enrollment”), any applicable fees (the “Subscription Fees”), and the payment schedule of such Subscription Fees (the “Payment Schedule”) with respect to each school will be agreed between such school and iSchoolManager pursuant to a separate Statement of Work agreed in writing by both parties (which may be done through execution or agreed online in the registration process). <br />
Upon such mutual agreement, such Statement of Work will become a part of (and is governed by) these Terms. <br />
Your Subscription will automatically renew for an additional Subscription month following the initial (and any renewal) Subscription month, unless you notify us no later than five (5) days prior to the end of any applicable Subscription month (the “Non-Renewal Period”) that you do not want to renew. <br />
In the event that your Subscription is renewed you must provide us with an updated Estimated Enrollment for the renewal Subscription month no later than 5 days after the start of such renewal Subscription month. Unless otherwise agreed to in writing between the parties, Subscription Fees for any renewal Subscription month will be due three (3) days before the start of the applicable renewal Subscription month. If you have chosen to be invoiced, your invoice will be sent prior to any applicable payment due dates, but will be due and payable on the dates set forth in the Payment Schedule or, if a renewal Subscription month, as described in the paragraph above. If you have provided us with a credit card details, we will charge the applicable account on each due date set forth in the Payment Schedule. If you have provided us inaccurate or inadequate payment information (including by providing us with a bad check), we will not be able to complete your transaction, and your account may be suspended until we have received payment in full. You may request to upgrade your Subscription to a more expensive Subscription during any Subscription month, by contacting iSchoolManager at <code>support@inovateos.com</code>. You will be required to pay the difference between the more-expensive Subscription and your then-current Subscription, pro-rated for the amount of time remaining in your then-current Subscription Term. Such payment will be made in accordance with the Statement of Work, and unless you tell us otherwise (within the Non-Renewal Period described above), your subscription will renew for the next Subscription month at the higher, upgraded rate. If you choose to downgrade to a less-expensive Subscription, you may also request that option at any time by contacting iSchoolManager at <code>support@inovateos.com</code>, provided that no refunds will be granted to you. <br /><br />The features of the Services may change from time to time. <br /><br />
In certain circumstances, including if the features of the Services are modified in a manner that materially adversely affects your use thereof, you may be entitled to a refund; refunds will only be granted as described herein. <br />
Notwithstanding the foregoing, you understand that iSchoolManager may freely modify the features of any Subscription and the Subscription Fees applicable to any Subscription between Subscription months. If iSchoolManager provides you notice of such changes after the end of the Non-Renewal Period for the then-current Subscription month (which may be provided via the Services or via email), and if you do not approve of such modifications, you may (as your sole remedy and iSchoolManager’s sole liability) provide iSchoolManager notice of your intent not to renew for the next Subscription within five (5) days of receipt of such notice form iSchoolManager.</p> <br />

<h3>What if I want to stop using iSchoolManager? </h3>
<p>You’re free to do that at any time, by contacting us at <code>support@inovateos.com</code>; please refer to our Privacy Policy, as well as the licenses above, to understand how we treat information you provide to us after you have stopped using our Services.<br /><br />
 If you have a student, parent, or teacher account, you understand that while you can stop using the Services whenever you want, your account can only be terminated by the school you are associated with, so you should ask the administrator of that account if you would like to terminate your account. Please note that if the applicable school that your student, parent, or teacher account is associated with does not have an active account, then your account may be deleted or made inaccessible. Also, the school you are associated with is able to terminate or suspend your account without iSchoolManager’s involvement; if a school chooses to terminate or suspend your account, iSchoolManager will not re-instate it without the school’s permission, and you should contact your school with questions. <br />
iSchoolManager is also free to terminate (or suspend access to) your use of the Services or your account, for any reason in our discretion, including your breach of these Terms. iSchoolManager has the sole right to decide whether you are in violation of any of the restrictions set forth in these Terms. <br />
Account termination (even if not initiated by iSchoolManager) may result in destruction of Content associated with your account. If you have deleted your school account by mistake, contact us immediately at <code>support@inovateos.com</code> – we will try to help, but unfortunately, we can’t promise that we can recover or restore anything. Provisions that, by their nature, should survive termination of these Terms shall survive termination.<br />
 By way of example, all of the following will survive termination: any obligation you have to pay us or indemnify us, any limitations on our liability, any terms regarding ownership of intellectual property rights, and terms regarding disputes between us. No refunds will be granted for amounts pre-paid prior to termination, except that if you terminate these Terms for <br />
(a) iSchoolManager’s material and substantiated breach hereof or <br />
(b) iSchoolManager’s modification of these Terms or of the features of the Services in a manner that materially adversely affects your use of the Services, we will grant you a pro-rata refund of amounts pre-paid by you for Services not received due to such termination; provided that you have notified us of your intent to terminate these Terms for either of these reasons promptly after the applicable breach or modification has occurred. </p><br />
<h3>What else do I need to know?</h3>
<p> Warranty Disclaimer. <br />Neither iSchoolManager nor its licensors or suppliers makes any representations or warranties concerning any content contained in or accessed through the Services, and we will not be responsible or liable for the accuracy, copyright compliance, legality, or decency of material contained in or accessed through the Services. We (and our licensors and suppliers) make no representations or warranties regarding suggestions or recommendations of services or products offered or purchased through the Services. <br />
THE SERVICES AND CONTENT ARE PROVIDED BY iSchoolManager (AND ITS LICENSORS AND SUPPLIERS) ON AN “AS-IS” BASIS, WITHOUT WARRANTIES OR ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. <br /><br />
Limitation of Liability. <br />TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, TORT, CONTRACT, STRICT LIABILITY, OR OTHERWISE) SHALL iSchoolManager (OR ITS LICENSORS OR SUPPLIERS) BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR <br />
(A) ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, OR <br />
(B) ANY AMOUNT, IN THE AGGREGATE, IN EXCESS OF THE GREATER OF (I) N10,000 OR (II) THE AMOUNTS PAID BY YOU TO iSchoolManager IN CONNECTION WITH THE SERVICES IN THE TWELVE (12) MONTH PERIOD PRECEDING THIS APPLICABLE CLAIM, OR (III) ANY MATTER BEYOND OUR REASONABLE CONTROL. <br /><br />
Indemnity. <br />To the fullest extent allowed by applicable law, you agree to indemnify and hold iSchoolManager, its affiliates, officers, agents, employees, and partners harmless from and against any and all claims, liabilities, damages (actual and consequential), losses and expenses (including attorneys’ fees) arising from or in any way related to any third party claims relating to <br />
(a) your use of the Services (including any actions taken by a third party using your account), and <br />
(b) your violation of these Terms. In the event of such a claim, suit, or action (“Claim”), we will attempt to provide notice of the Claim to the contact information we have for your account (provided that failure to deliver such notice shall not eliminate or reduce your indemnification obligations hereunder). <br /><br />
Assignment. <br />
You may not assign, delegate or transfer these Terms or your rights or obligations hereunder, or your Services account, in any way (by operation of law or otherwise) without iSchoolManager’s prior written consent. We may transfer, assign, or delegate these Terms and our rights and obligations without consent. Miscellaneous. The failure of either you or us to exercise, in any way, any right herein shall not be deemed a waiver of any further rights hereunder. If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated, to the minimum extent necessary, so that these Terms shall otherwise remain in full force and effect and enforceable. <br />You and iSchoolManager agree that these Terms are the complete and exclusive statement of the mutual understanding between you and iSchoolManager, and that it supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of these Terms. <br />You hereby acknowledge and agree that you are not an employee, agent, partner, or joint venture of iSchoolManager, and you do not have any authority of any kind to bind iSchoolManager in any respect whatsoever. If you have a school account, you grant us the right to use your school’s name in our publicity and marketing materials.</p>
</div>
          </div>
                    </div>

            </div>
            
                        </div>
    )
}

export default Terms
